server:
  port: 8081
mybatis:
  type-aliases-package: cxt.cn.pojo
spring:
  datasource:
    url: jdbc:mysql:///ceshi?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  application:
    name: SpringCloudServiceProvider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

