server:
  port: 8082
spring:
  application:
    name: SpringCloudServiceConsumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
