server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  routes:
    SpringCloudServiceProvider:
      path: /SpringCloudServiceProvider/**
      serviceId: SpringCloudServiceProvider
#      url: http://localhost:8081

spring:
  application:
    name: zuul
